/*

 MAPTESTE2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\Glenio Lobo\Desktop\Faculdade\Interface Hardware Software\pong-souls\assets-test\b1.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define MapTeste2Width 20
#define MapTeste2Height 18
#define MapTeste2Bank 0

extern unsigned char MapTeste2[];

/* End of MAPTESTE2.H */
