/*

 BACKGROUNDPONG.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\crist\Documents\linhaDaQuadra.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define BackgroundPongWidth 20
#define BackgroundPongHeight 18
#define BackgroundPongBank 0

extern unsigned char BackgroundPong[];

/* End of BACKGROUNDPONG.H */
